# Site
name: "covid-19 health data for NHS data-scientists"
title: "covid-19 health data for NHS data-scientists"
description: "Public data-store on Github"
meta_description: "Public data-store on Github"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'ian.kilby@thethingthatiwant.com'
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Dug
    display_name: Dug
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: ian.kilby@thethingthatiwant.com
    web: https://www.donkeyontheedge.com
    twitter: https://twitter.com/dug
    description: "me, ok?"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

